# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib cptkirk, .registration = TRUE
NULL

#' Open a source (local path, http(s)://, s3://, gs://, az://). Returns an
#' external pointer reused by `cog_meta()` / `cog_fetch_window()`.
#' @noRd
cog_open <- function(src, opt_keys, opt_vals) .Call(wrap__cog_open, src, opt_keys, opt_vals)

#' Structural + georeferencing metadata for an open source.
#' @noRd
cog_meta <- function(h) .Call(wrap__cog_meta, h)

#' Concurrently open several sources and return their metadata.
#'
#' Opens all `srcs` in a single runtime pass (overlapping the metadata
#' round-trips) and returns a list with one `read_cog_meta`-style entry per
#' source, in order. Used to plan a multi-tile mosaic without paying the opens
#' sequentially.
#' @noRd
cog_meta_many <- function(srcs, opt_keys, opt_vals) .Call(wrap__cog_meta_many, srcs, opt_keys, opt_vals)

#' Fetch a pixel window of an overview level from an open source. `level` is
#' 1-based (1 = full resolution); `bands` is 1-based (empty = all). Returns a
#' list with `data` (band-sequential double vector), `xsize`, `ysize`,
#' `n_bands`.
#' @noRd
cog_fetch_window <- function(h, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency) .Call(wrap__cog_fetch_window, h, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency)

#' Fetch a pixel window as a NATIVE-dtype byte buffer (band-sequential,
#' native endianness) for staging a `/vsimem` raster. `level`/`bands` as in
#' `cog_fetch_window`. Returns a list with `bytes` (raw vector), `xsize`,
#' `ysize`, `n_bands`, `dtype` (GDAL type name), `bytes_per_sample`, and
#' `byte_order` ("LSB"/"MSB").
#' @noRd
cog_fetch_window_raw <- function(h, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency) .Call(wrap__cog_fetch_window_raw, h, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency)

#' Concurrently fetch one native-dtype window from each of several sources.
#'
#' `srcs` and the per-tile `level`/`xoff`/`yoff`/`xsize`/`ysize` vectors are
#' parallel (one entry per tile). `bands` (1-based, empty = all) and `fill`
#' are shared across tiles. All sources are opened and their windows fetched
#' within a single runtime, so the tiles' network reads overlap. Returns a
#' list with one element per tile, each as in `cog_fetch_window_raw`.
#' @noRd
cog_fetch_windows_raw <- function(srcs, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency, opt_keys, opt_vals) .Call(wrap__cog_fetch_windows_raw, srcs, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency, opt_keys, opt_vals)

#' Open many sources concurrently. Returns `list(ptr, metas)`: a reusable
#' handle plus per-source metadata for window planning. The header is read here
#' once; the subsequent stream fetches reuse the open handles.
#' @noRd
cog_sources_open <- function(srcs, opt_keys, opt_vals) .Call(wrap__cog_sources_open, srcs, opt_keys, opt_vals)

#' Begin streaming the requested per-source windows from an open `SourceSet`.
#' `idx` is 1-based into the set; the parallel `level/xoff/...` vectors give each
#' requested window. Returns a session handle; drain it with `cog_fetch_take`.
#' @noRd
cog_fetch_stream_begin <- function(set, idx, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency) .Call(wrap__cog_fetch_stream_begin, set, idx, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency)

#' Like `cog_fetch_stream_begin`, but opens each source inside its own fetch
#' task (from URLs, no pre-opened SourceSet) so the per-source open overlaps the
#' fetch instead of forming an open-all barrier. The caller must already know
#' the window for every source (e.g. a trusted single grid planned from one
#' source). `index` in the stream is 1-based into `srcs`.
#' @noRd
cog_stream_fetch_urls_begin <- function(srcs, opt_keys, opt_vals, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency) .Call(wrap__cog_stream_fetch_urls_begin, srcs, opt_keys, opt_vals, level, xoff, yoff, xsize, ysize, bands, fill, io_concurrency)

#' Block for the next completed window (any source, completion order). Returns a
#' `list(index, bytes, xsize, ysize, n_bands, dtype, bytes_per_sample,
#' byte_order)` (`index` 1-based into the SourceSet), `list(index, error)` on a
#' per-source failure, or `NULL` when the stream is fully drained.
#' @noRd
cog_fetch_take <- function(sess) .Call(wrap__cog_fetch_take, sess)

# nolint end
